server:
  port: ${PORT:${SERVERS_PORT:0}}
spring:
  application:
    name: ms-wallet-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/ms_wallet
    username: root
    password: 124578369scar@
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8010/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    ms-categories-service:
      register-health-indicator: true
      sliding-window-size: 10
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      automatic-transition-from-open-to-half-open-enabled: true
      permitted-number-of-calls-in-half-open-state: 3
    ms-events-service:
      register-health-indicator: true
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      automatic-transition-from-open-to-half-open-enabled: true
    ms-auth-service:
      register-health-indicator: true
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
